#pragma once

#define ICON_DEFAULT 100

#define TRAY_MENU 2200
#define TRAY_MENU_SHOW (TRAY_MENU+1)
#define TRAY_MENU_CLOSE (TRAY_MENU+2)

#define CONTEXT_MENU 2300
#define CONTEXT_MENU_RESET_SIZE (CONTEXT_MENU+1)
#define CONTEXT_MENU_COPY_HOSTNAME (CONTEXT_MENU+2)
#define CONTEXT_MENU_COPY_STATUS (CONTEXT_MENU+3)
#define CONTEXT_MENU_COPY_ROUTE (CONTEXT_MENU+4)
#define CONTEXT_MENU_SAVE_LOG (CONTEXT_MENU+5)
#define CONTEXT_MENU_ALWAYS_ON_TOP (CONTEXT_MENU+6)
